feat: poc requirement
pagopa/mil-termsandconds pull request #1
Opened 2023-01-23 11:13 UTC by fabrizioacn

2023-01-30 15:24 UTC, antoniotarricone requested changes
Code comments are mostly not present, pay attention to the indentation, see every feedback reported in several files.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/PmWalletService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
Move this client in it.gov.pagopa.swclient.mil.termsandconds.client.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TokensService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
Move this client in it.gov.pagopa.swclient.mil.termsandconds.client.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/SessionService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
Move this client in it.gov.pagopa.swclient.mil.termsandconds.client.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TokenBody.java
> +	public String toString() {
To avoid unwanted exposure of sensitive data, it is best to remove this method.

2023-01-30 15:24 UTC, antoniotarricone commented on pom.xml
>  		<quarkus.platform.version>2.14.3.Final</quarkus.platform.version>
Switch to 2.16.0.Final.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/SaveNewCardsResponse.java
> +		return "SaveNewCards [saveNewCards=" + saveNewCards + "]";
Use StringBuilder.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/SessionResponse.java
> +		builder .append("TermsAndConds session response [outcome=").append(outcome)
Replace "TermsAndConds session response" with "SessionResponse".

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/SessionResponse.java
> +				.append(" taxCode=").append(taxCode)
taxCode is a personal data and must not be exposed.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TCHeaderParams.java
> +		return super.toString() + "TCHeaderParams [sessionId=" + sessionId + "]";
Use StringBuilder.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TCHeaderParams.java
> +	@NotNull(message = "[" + ErrorCode.SESSION_ID_MUST_NOT_BE_NULL + "] RequestId must not be null")
There is a typo: replace "RequestId" with "SessionId".

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TCHeaderParams.java
> +	@Pattern(regexp = "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$", message = "[" + ErrorCode.SESSION_ID_MUST_MATCH_REGEXP + "] RequestId must match \"{regexp}\"")
There is a type: replace "RequestId" with "SessionId".

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TcPathParam.java
> +public class TcPathParam {
Be coherent with naming convention: rename the class in "TCPathParam".

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TcPathParam.java
> +public class TcPathParam {
Is it really needed?

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +						Log.errorf(t, "Version not found in the DB for taxCode %s",pathParams.getTaxCode());
Tax code must not be written in logs.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/SessionService.java
> +    Uni<SaveNewCardsResponse> patchSessionById(@PathParam("sessionId") String sessionId, @BeanParam CommonHeader commonHeader, SessionRequest request);
The PATCH method of Session Service doesn't return the flag "save new card"!

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TokenBody.java
> +public class TokenBody {
Rename in TokenRequest.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("getTermsAndConds - Input parameters: %s, taxCode: %s", headers, pathParams.getTaxCode());
Tax code must not be written in logs.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +								.entity(new Errors(List.of(ErrorCode.ERROR_VERSION_NOT_FOUND_SERVICE)))
"ERROR_VERSION_NOT_FOUND_SERVICE" is a little bit confusing. "VERSION_NOT_FOUND" is better.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +							Log.errorf(t, "[%s] Internal server errorError calling tokenizator service ", ErrorCode.ERROR_VERSION_NOT_FOUND_SERVICE);
The error code should be "ERROR_VERSION_SERVICE" and not "ERROR_VERSION_NOT_FOUND_SERVICE".

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/SessionResponse.java
> +	private String outcome;
This must be an enum and not a String.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("manageTokenResponse -  taxCode= %s",taxCode);
Tax code must not be written in logs.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("saveNewCard -  taxCode= %s", taxCode);
Tax code must not be written in logs.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +	@ConfigProperty(name="terms.conds")
Must be read from DB.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("manageUpinsert - version= %s - for taxCode token= %s", tcVersion, taxCodeToken);
Tax code must not be written in logs.

2023-01-30 15:24 UTC, antoniotarricone commented on src/main/resources/application.properties
> +%dev.activate.paymentnotice.expiration.time=${activate.paymentnotice.expiration.time}
Where is this property used?

2023-01-31 16:30 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/PmWalletService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
fixed

2023-01-31 16:30 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TokensService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/SessionService.java
> +package it.gov.pagopa.swclient.mil.termsandconds.resource;
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TokenBody.java
> +	public String toString() {
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on pom.xml
>  		<quarkus.platform.version>2.14.3.Final</quarkus.platform.version>
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("manageTokenResponse -  taxCode= %s",taxCode);
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("saveNewCard -  taxCode= %s", taxCode);
fixed

2023-01-31 16:31 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +	@ConfigProperty(name="terms.conds")
fixed

2023-01-31 16:32 UTC, fabrizioacn commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("manageUpinsert - version= %s - for taxCode token= %s", tcVersion, taxCodeToken);
fixed

2023-01-31 16:32 UTC, fabrizioacn commented on src/main/resources/application.properties
> +%dev.activate.paymentnotice.expiration.time=${activate.paymentnotice.expiration.time}
removed unused.
fixed

2023-05-17 07:01 UTC, antoniotarricone approved these changes

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +		Log.debugf("getTermsAndConds - Input parameters: %s, taxCode: %s", headers, pathParams.getTaxCode());
Tax code is still written in logs!

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/SessionResponse.java
> +				.append(" taxCode=").append(taxCode)
The issue is still pending.

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TCHeaderParams.java
> +	@NotNull(message = "[" + ErrorCode.SESSION_ID_MUST_NOT_BE_NULL + "] RequestId must not be null")
The issue is still present.

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TCHeaderParams.java
> +	@Pattern(regexp = "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$", message = "[" + ErrorCode.SESSION_ID_MUST_MATCH_REGEXP + "] RequestId must match \"{regexp}\"")
The issue is still present.

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TcPathParam.java
> +public class TcPathParam {
The issue is still there.

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TcPathParam.java
> +public class TcPathParam {
Again... is it really needed?

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/SessionService.java
> +    Uni<SaveNewCardsResponse> patchSessionById(@PathParam("sessionId") String sessionId, @BeanParam CommonHeader commonHeader, SessionRequest request);
The issue is still there!

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/bean/TokenBody.java
> +public class TokenBody {
The issue is still there!

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +								.entity(new Errors(List.of(ErrorCode.ERROR_VERSION_NOT_FOUND_SERVICE)))
The issue is still there!

2023-05-17 07:01 UTC, antoniotarricone commented on src/main/java/it/gov/pagopa/swclient/mil/termsandconds/resource/TermAndCondsResource.java
> +							Log.errorf(t, "[%s] Internal server errorError calling tokenizator service ", ErrorCode.ERROR_VERSION_NOT_FOUND_SERVICE);
The issue is still there.

2023-05-17 07:03 UTC, antoniotarricone approved these changes

2023-05-17 07:03 UTC, merged